name: Build and Publish Prebuilt Binaries
on: [push]
jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: windows-x64
            os: windows-latest
            arch: x64
    steps:
      - uses: actions/checkout@v5

      - uses: lukka/get-cmake@latest

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      
      - name: Build
        run: |
          cmake -B build -S . ${{ matrix.cmake_args }} -DCMAKE_BUILD_TYPE=Release -DASSIMP_BUILD_TESTS=OFF -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF -DASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT=OFF -DASSIMP_BUILD_GLTF_IMPORTER=ON
          cmake --build build --config Release

      - uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: ${{ matrix.name }}.zip
          directory: build/bin/

      - uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: ${{ matrix.name }}.zip
          directory: build/lib/

      - uses: actions/upload-artifact@v4
        with:
          name: library artifact
          path: build/library/${{ matrix.name }}.zip
          
      - uses: actions/upload-artifact@v4
        with:
          name: binary artifact
          path: build/bin/${{ matrix.name }}.zip
          
