name: Build and Publish Prebuilt Binaries

on:
  release:
    types: [created]
    
jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: windows-x64
            os: windows-latest
            arch: x64
    steps:
      - uses: actions/checkout@v5

      - uses: lukka/get-cmake@latest

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      
      - name: Build
        run: |
          cmake -B build -S . ${{ matrix.cmake_args }} -DCMAKE_BUILD_TYPE=Release -DASSIMP_BUILD_TESTS=OFF
          cmake --build build --config Release
          
      - name: list files
        run: |
          ls
          cd build
          ls
          cd ../
          ls

      - uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: ${{ matrix.name }}-${{ github.event.release.tag_name }}.zip
          directory: build/bin/

      - uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: ${{ matrix.name }}-${{ github.event.release.tag_name }}.zip
          directory: build/lib/

      - uses: softprops/action-gh-release@v2
        with:
          files: build/bin/${{ matrix.name }}-${{ github.event.release.tag_name }}.zip
          append_body: true
          fail_on_unmatched_files: true
